# This is a basic workflow to help you get started with Actions

name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
      - name: install dependencies
        run: npm ci
      - name: Build
        run: CI=false npm run build
        env:
          VITE_APP_GA: ${{ secrets.GOOGLE_ANALYTICS }}
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.
